<li>
        <div class="item"> <a href="[field:arcurl/]" class="fl"><img src="[field:litpic/]" /></a>
          <div class="zr">
            <p><a href="[field:arcurl/]"><b>[field:title/]</b><span>[field:shorttitle/]</span></a></p>

            <div class="ZJ_jianjie">[field:infos/]…<span><a href="[field:arcurl/]">[详细]</a></span></div>
            <p><a href="" class="ZJ_p3b">预约挂号</a></p>
          </div>
        </div>
      </li>