<li>
          <div class="zglcc_p1"><a href="[field:arcurl/]">[field:title/]</a><span class="fr">[[field:click/]阅读]</span></div>
          <div class="zglcc_p2 clear"><a href="[field:arcurl/]">[field:infos/]…<span>[详情]</span></a></div>
          <div class="zglcc_p3"><a href="[field:arcurl/]" class="zglcc_p3a">在线咨询</a><a href="tel:02884319120" class="zglcc_p3b">028-84319120</a></div>
        </li>