<?php
$z[0]=Array("global","",69,101);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",386,418);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",485,517);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",580,612);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",676,708);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",772,804);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",866,898);
$z[6][4]['name']="cfg_templets_skin";

?>